### ISSUE TITLE
OS X 10.10 Yosemite unsupported

### ISSUE THREAD

**Issue by danielhauagge** [kolinkrewinkel/Multiplex#22]
Hi, 

Thanks for making this plugin, it implements one of my favorite features of SublimeText! I haven't been able to get it to work though. I tried installing it with Alcatraz but it didn't seem to work. Then I ran the installer, which worked. Now I try to select multiple instances of a word with the command+d shortcut but nothing gets selected. I know this isn't super helpful as a bug report, so if you can tell me where to look for logs that could point out what is going on I'd appreciate that.

D

**Comment by kolinkrewinkel** [comment]
Unfortunately as far as functional bugs go, there's no logging. The install itself was completed, so does it let you perform multi-selection at all? As in, is it specific to the Quick Add Next feature?

**Comment by danielhauagge** [comment]
None of the shortcuts work.

**Comment by kolinkrewinkel** [comment]
When you drag a selection, does the blinking caret hide away, or stay? (That's the easiest way to tell if it's actually installed and functioning.)

**Comment by danielhauagge** [comment]
It stays.

**Comment by kolinkrewinkel** [comment]
Hmm...does it work if you select the menu item from the Find menu? Trying to determine if it's a bug with finding and selecting the string or just triggering the action in the first place...

**Comment by danielhauagge** [comment]
What item should I select? This is what my find menu looks like.
![screenshot 2015-10-23 09 40 59](https://cloud.githubusercontent.com/assets/1358818/10694082/347627a4-796a-11e5-87a0-b95444dcd97e.png)

**Comment by kolinkrewinkel** [comment]
It should be at the bottom, entitled "Quick Add Next." So this is a bug with adding that menu item, it seems, provided that the other stuff is working. I'll look into it.

![ss 2015-10-23 at 09 32 05](https://cloud.githubusercontent.com/assets/143944/10699051/f1c8a446-7968-11e5-9e5b-77b7632ec40d.png)

**Comment by kolinkrewinkel** [comment]
Unfortunately this is an issue with Multiplex using CocoaPods and Alcatraz not being able to set them up when it clones them. Unfortunately that means Alcatraz is unsupported. Cloning, `pod install`, and building is the best option for keeping it up to date and quickly installing; alternatively, you can download the plugin binary or an installer from the Releases page.

**Comment by danielhauagge** [comment]
I installed the plugin on a different machine, using the installer, and it doesn't work either. This one is running Xcode 7.0.1 and has Alcatraz installed.

**Comment by kolinkrewinkel** [comment]
Can you check the Console for any relevant output when starting up Xcode? Also, it would be good to verify that the plugin is located in ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/

**Comment by danielhauagge** [comment]
OK, now I think we found the reason. I'm running Yosemite and it seems like your plugin was built for EC. Here's the log:

```
10/26/15 9:18:01.668 AM Xcode[99349]: WARNING: Failed to load plugin at path: "/Users/XXXXXXX/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Multiplex.xcplugin", skipping. Error: Error Domain=NSCocoaErrorDomain Code=3588 "The bundle “Multiplex” couldn’t be loaded." (dlopen(/Users/XXXXXXX/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Multiplex.xcplugin/Contents/MacOS/Multiplex, 265): Symbol not found: ___NSDictionary0__
  Referenced from: /Users/XXXXXXX/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Multiplex.xcplugin/Contents/MacOS/../Frameworks/MPXSelectionCore.framework/Versions/A/MPXSelectionCore (which was built for Mac OS X 10.11)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 in /Users/XXXXXXX/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Multiplex.xcplugin/Contents/MacOS/../Frameworks/MPXSelectionCore.framework/Versions/A/MPXSelectionCore) UserInfo=0x7f91fb435130 {NSLocalizedFailureReason=The bundle couldn’t be loaded., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/XXXXXXX/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Multiplex.xcplugin/Contents/MacOS/Multiplex, NSDebugDescription=dlopen(/Users/XXXXXXX/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Multiplex.xcplugin/Contents/MacOS/Multiplex, 265): Symbol not found: ___NSDictionary0__
  Referenced from: /Users/XXXXXXX/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Multiplex.xcplugin/Contents/MacOS/../Frameworks/MPXSelectionCore.framework/Versions/A/MPXSelectionCore (which was built for Mac OS X 10.11)
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 in /Users/XXXXXXX/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Multiplex.xcplugin/Contents/MacOS/../Frameworks/MPXSelectionCore.framework/Versions/A/MPXSelectionCore, NSBundlePath=/Users/XXXXXXX/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Multiplex.xcplugin, NSLocalizedDescription=The bundle “Multiplex” couldn’t be loaded.}
```

**Comment by kolinkrewinkel** [comment]
Ah...it's probably totally safe for me to add support for Yosemite, so I'll do that.

**Comment by maurice-schleussinger** [comment]
So there is no hotfix yet? 

I can`t manually build the current commit in Xcode...

**Comment by kolinkrewinkel** [comment]
What's the error? I removed the frameworks inside that were depending on 10.11, so it should build on 10.9 and up now.

**Comment by kolinkrewinkel** [comment]
Closing this issue since I'm pretty sure it's resolved.
