### ISSUE TITLE
Support for Cmd+D to select next occurrence

### ISSUE THREAD

**Issue by macecchi** [kolinkrewinkel/Multiplex#32]
Add support to **⌘+D** to select next occurrence of the selected text (as in Sublime)? 

This is **kind of** similar to "Edit all in scope" except that it could work with any selection, not just variable names.

**Comment by kolinkrewinkel** [comment]
This is already supported, but it wasn't working for a little bit. The latest installer should include this feature; please let me know if you do/don't get it working :)

**Comment by kolinkrewinkel** [comment]
Ah, so in most recent one it's in the Find menu but the keyboard shortcut isn't working. I'll look into this.

**Comment by macecchi** [comment]
That was quick! Thanks :)

**Comment by samuelbeek** [comment]
CMD + D doesn't work with me... rest of the plugin works; can't find what's causing this.

**Comment by takuoka** [comment]
@samuelbeek +1

**Comment by kolinkrewinkel** [comment]
@samuelbeek, @entotsu: Are you running the 1.0.1 binary/installer version? If compiling it locally makes it work, it's just because that commit's missing...I should add another release.

**Comment by kolinkrewinkel** [comment]
Should be fixed when building from source, and using the latest binary/installer [here](https://github.com/kolinkrewinkel/Multiplex/releases/tag/v1.0.2). Let me know if you have any issues. :sweat_smile:

**Comment by samuelbeek** [comment]
thanks!

**Comment by aokabin** [comment]
@kolinkrewinkel 
I installed 1.0.2 in Xcode7.2 with Alcatraz.
Edit All in Scope(Ctrl + Cmd +E) is woking.
But Select Next Occurrence(Cmd+D) doesn't work my Xcode...
What should I do?

**Comment by kolinkrewinkel** [comment]
@aokabin Alcatraz isn't supported to install. There is a binary and installer is available on the releases page

**Comment by ghost** [comment]
This is not working in Swift, if Swift is not supported, I'll shut up. Built latest version (1.2), Edit all in scope works with multiline edit, so does alt-click, but not cmd-D.
