### ISSUE TITLE
How to uninstall (installer.pkg)

### ISSUE THREAD

**Issue by takuoka** [kolinkrewinkel/Multiplex#33]
Thank you for making awesome plugin.

I installed this plugin from `installer.pkg`.
How can I uninstall plugin?

(I want to re-install plugin with manual way. Because Cmd-D is not working.)

**Comment by kolinkrewinkel** [comment]
You can delete it at `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/`
If you compile it, it'll just overwrite the existing file. :)

**Comment by takuoka** [comment]
Thank you for reply. :bow: 

I can't find the plugin in `~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/`.
But, this plugin is working.

And I download latest `Multiplex.xcplugin` and move it to there, Then Xcode crush when launch.

Where is install directory of `installer.pkg`?

**Comment by takuoka** [comment]
Xcode is still crush sometimes. :sob:

**Comment by takuoka** [comment]
I can't uninstall this plugin completely... :sob:

**Comment by takuoka** [comment]
I removed some directory then my Xcode come clean. :+1: 

>  For complete removal Xcode 7 you should remove
> - /Apllications/Xcode.app
> - /Library/Preferences/com.apple.dt.Xcode.plist
> - ~/Library/Preferences/com.apple.dt.Xcode.plist
> - ~/Library/Caches/com.apple.dt.Xcode
> - ~/Library/Application Support/Xcode

http://stackoverflow.com/a/33812614

**Comment by kolinkrewinkel** [comment]
Glad you got it figured out!
