### ISSUE TITLE
Loosing ⌘+click feature

### ISSUE THREAD

**Issue by leolelego** [kolinkrewinkel/Multiplex#38]
When Multiplex is installed, I loose the Xcode feature to do ⌘+click on an object to display it declaration/sources. The feature is moved to ⌥+click but this key is user to another feature which is not accessible with Multiplex installed.

**Comment by leolelego** [comment]
OK, I re-read your README. Can you add an option to change the key associated to you plugin ?

**Comment by kolinkrewinkel** [comment]
Yep, we're tracking this in #16.
